release:
  prerelease: auto
  draft: true

builds:
  - binary: &binary docker-base
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    env: &build-env
      - CGO_ENABLED=0
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X github.com/docker/base-cli-plugin/internal.version={{.Version}}
      -X github.com/docker/base-cli-plugin/internal.commit={{.Commit}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
